//! Seccomp filter for Windows Module hybrid libraries

use std::sync::atomic::{AtomicBool, Ordering};

#[cfg(feature = "seccomp")]
use seccomp::{SeccompAction, SeccompFilter, SyscallRuleSet};

pub struct WindowsSeccompFilter {
    enabled: AtomicBool,
}

impl WindowsSeccompFilter {
    pub fn new(enable_by_default: bool) -> Self {
        Self {
            enabled: AtomicBool::new(enable_by_default),
        }
    }

    #[cfg(feature = "seccomp")]
    pub fn create_filter(&self) -> SeccompFilter {
        let allow_rules = vec![
            SyscallRuleSet::new_allow("read"),
            SyscallRuleSet::new_allow("write"),
            SyscallRuleSet::new_allow("open"),
            SyscallRuleSet::new_allow("close"),
            SyscallRuleSet::new_allow("mprotect"),
            SyscallRuleSet::new_allow("mmap"),
            SyscallRuleSet::new_allow("munmap"),
            SyscallRuleSet::new_allow("brk"),
            SyscallRuleSet::new_allow("rt_sigaction"),
            SyscallRuleSet::new_allow("rt_sigprocmask"),
            SyscallRuleSet::new_allow("ioctl"),
            SyscallRuleSet::new_allow("readv"),
            SyscallRuleSet::new_allow("writev"),
            SyscallRuleSet::new_allow("access"),
            SyscallRuleSet::new_allow("pipe"),
            SyscallRuleSet::new_allow("select"),
            SyscallRuleSet::new_allow("mremap"),
            SyscallRuleSet::new_allow("msync"),
            SyscallRuleSet::new_allow("mincore"),
            SyscallRuleSet::new_allow("madvise"),
            SyscallRuleSet::new_allow("shmget"),
            SyscallRuleSet::new_allow("shmat"),
            SyscallRuleSet::new_allow("shmctl"),
            SyscallRuleSet::new_allow("dup"),
            SyscallRuleSet::new_allow("dup2"),
            SyscallRuleSet::new_allow("pause"),
            SyscallRuleSet::new_allow("nanosleep"),
            SyscallRuleSet::new_allow("getitimer"),
            SyscallRuleSet::new_allow("alarm"),
            SyscallRuleSet::new_allow("setitimer"),
            SyscallRuleSet::new_allow("getpid"),
            SyscallRuleSet::new_allow("socket"),
            SyscallRuleSet::new_allow("connect"),
            SyscallRuleSet::new_allow("accept"),
            SyscallRuleSet::new_allow("sendto"),
            SyscallRuleSet::new_allow("recvfrom"),
            SyscallRuleSet::new_allow("sendmsg"),
            SyscallRuleSet::new_allow("recvmsg"),
            SyscallRuleSet::new_allow("shutdown"),
            SyscallRuleSet::new_allow("bind"),
            SyscallRuleSet::new_allow("listen"),
            SyscallRuleSet::new_allow("getsockname"),
            SyscallRuleSet::new_allow("getpeername"),
            SyscallRuleSet::new_allow("socketpair"),
            SyscallRuleSet::new_allow("setsockopt"),
            SyscallRuleSet::new_allow("getsockopt"),
            SyscallRuleSet::new_allow("clone"),
            SyscallRuleSet::new_allow("fork"),
            SyscallRuleSet::new_allow("vfork"),
            SyscallRuleSet::new_allow("execve"),
            SyscallRuleSet::new_allow("exit"),
            SyscallRuleSet::new_allow("wait4"),
            SyscallRuleSet::new_allow("kill"),
            SyscallRuleSet::new_allow("uname"),
            SyscallRuleSet::new_allow("semget"),
            SyscallRuleSet::new_allow("semop"),
            SyscallRuleSet::new_allow("semctl"),
            SyscallRuleSet::new_allow("shmdt"),
            SyscallRuleSet::new_allow("msgget"),
            SyscallRuleSet::new_allow("msgsnd"),
            SyscallRuleSet::new_allow("msgrcv"),
            SyscallRuleSet::new_allow("msgctl"),
            SyscallRuleSet::new_allow("fcntl"),
            SyscallRuleSet::new_allow("flock"),
            SyscallRuleSet::new_allow("fsync"),
            SyscallRuleSet::new_allow("truncate"),
            SyscallRuleSet::new_allow("ftruncate"),
            SyscallRuleSet::new_allow("getdents"),
            SyscallRuleSet::new_allow("getcwd"),
            SyscallRuleSet::new_allow("chdir"),
            SyscallRuleSet::new_allow("rename"),
            SyscallRuleSet::new_allow("mkdir"),
            SyscallRuleSet::new_allow("rmdir"),
            SyscallRuleSet::new_allow("creat"),
            SyscallRuleSet::new_allow("link"),
            SyscallRuleSet::new_allow("unlink"),
            SyscallRuleSet::new_allow("symlink"),
            SyscallRuleSet::new_allow("readlink"),
            SyscallRuleSet::new_allow("chmod"),
            SyscallRuleSet::new_allow("fchmod"),
            SyscallRuleSet::new_allow("chown"),
            SyscallRuleSet::new_allow("fchown"),
            SyscallRuleSet::new_allow("lchown"),
            SyscallRuleSet::new_allow("umask"),
            SyscallRuleSet::new_allow("gettimeofday"),
            SyscallRuleSet::new_allow("getrlimit"),
            SyscallRuleSet::new_allow("getrusage"),
            SyscallRuleSet::new_allow("sysinfo"),
            SyscallRuleSet::new_allow("times"),
            SyscallRuleSet::new_allow("ptrace"),
            SyscallRuleSet::new_allow("getuid"),
            SyscallRuleSet::new_allow("syslog"),
            SyscallRuleSet::new_allow("getgid"),
            SyscallRuleSet::new_allow("setuid"),
            SyscallRuleSet::new_allow("setgid"),
            SyscallRuleSet::new_allow("geteuid"),
            SyscallRuleSet::new_allow("getegid"),
            SyscallRuleSet::new_allow("setpgid"),
            SyscallRuleSet::new_allow("getppid"),
            SyscallRuleSet::new_allow("getpgrp"),
            SyscallRuleSet::new_allow("setsid"),
            SyscallRuleSet::new_allow("setreuid"),
            SyscallRuleSet::new_allow("setregid"),
            SyscallRuleSet::new_allow("getgroups"),
            SyscallRuleSet::new_allow("setgroups"),
            SyscallRuleSet::new_allow("setresuid"),
            SyscallRuleSet::new_allow("getresuid"),
            SyscallRuleSet::new_allow("setresgid"),
            SyscallRuleSet::new_allow("getresgid"),
            SyscallRuleSet::new_allow("getpgid"),
            SyscallRuleSet::new_allow("setfsuid"),
            SyscallRuleSet::new_allow("setfsgid"),
            SyscallRuleSet::new_allow("getsid"),
            SyscallRuleSet::new_allow("capget"),
            SyscallRuleSet::new_allow("capset"),
            SyscallRuleSet::new_allow("rt_sigpending"),
            SyscallRuleSet::new_allow("rt_sigtimedwait"),
            SyscallRuleSet::new_allow("rt_sigqueueinfo"),
            SyscallRuleSet::new_allow("rt_sigsuspend"),
            SyscallRuleSet::new_allow("sigaltstack"),
            SyscallRuleSet::new_allow("utime"),
            SyscallRuleSet::new_allow("mknod"),
            SyscallRuleSet::new_allow("uselib"),
            SyscallRuleSet::new_allow("personality"),
            SyscallRuleSet::new_allow("ustat"),
            SyscallRuleSet::new_allow("statfs"),
            SyscallRuleSet::new_allow("fstatfs"),
            SyscallRuleSet::new_allow("sysfs"),
            SyscallRuleSet::new_allow("getpriority"),
            SyscallRuleSet::new_allow("setpriority"),
            SyscallRuleSet::new_allow("sched_setparam"),
            SyscallRuleSet::new_allow("sched_getparam"),
            SyscallRuleSet::new_allow("sched_setscheduler"),
            SyscallRuleSet::new_allow("sched_getscheduler"),
            SyscallRuleSet::new_allow("sched_get_priority_max"),
            SyscallRuleSet::new_allow("sched_get_priority_min"),
            SyscallRuleSet::new_allow("sched_rr_get_interval"),
            SyscallRuleSet::new_allow("mlock"),
            SyscallRuleSet::new_allow("munlock"),
            SyscallRuleSet::new_allow("mlockall"),
            SyscallRuleSet::new_allow("munlockall"),
            SyscallRuleSet::new_allow("vhangup"),
            SyscallRuleSet::new_allow("modify_ldt"),
            SyscallRuleSet::new_allow("pivot_root"),
            SyscallRuleSet::new_allow("prctl"),
            SyscallRuleSet::new_allow("arch_prctl"),
            SyscallRuleSet::new_allow("adjtimex"),
            SyscallRuleSet::new_allow("setrlimit"),
            SyscallRuleSet::new_allow("chroot"),
            SyscallRuleSet::new_allow("sync"),
            SyscallRuleSet::new_allow("acct"),
            SyscallRuleSet::new_allow("settimeofday"),
            SyscallRuleSet::new_allow("mount"),
            SyscallRuleSet::new_allow("umount2"),
            SyscallRuleSet::new_allow("swapon"),
            SyscallRuleSet::new_allow("swapoff"),
            SyscallRuleSet::new_allow("reboot"),
            SyscallRuleSet::new_allow("sethostname"),
            SyscallRuleSet::new_allow("setdomainname"),
            SyscallRuleSet::new_allow("iopl"),
            SyscallRuleSet::new_allow("ioperm"),
            SyscallRuleSet::new_allow("init_module"),
            SyscallRuleSet::new_allow("delete_module"),
            SyscallRuleSet::new_allow("quotactl"),
            SyscallRuleSet::new_allow("gettid"),
            SyscallRuleSet::new_allow("readahead"),
            SyscallRuleSet::new_allow("setxattr"),
            SyscallRuleSet::new_allow("lsetxattr"),
            SyscallRuleSet::new_allow("fsetxattr"),
            SyscallRuleSet::new_allow("getxattr"),
            SyscallRuleSet::new_allow("lgetxattr"),
            SyscallRuleSet::new_allow("fgetxattr"),
            SyscallRuleSet::new_allow("listxattr"),
            SyscallRuleSet::new_allow("llistxattr"),
            SyscallRuleSet::new_allow("flistxattr"),
            SyscallRuleSet::new_allow("removexattr"),
            SyscallRuleSet::new_allow("lremovexattr"),
            SyscallRuleSet::new_allow("fremovexattr"),
            SyscallRuleSet::new_allow("tkill"),
            SyscallRuleSet::new_allow("time"),
            SyscallRuleSet::new_allow("futex"),
            SyscallRuleSet::new_allow("sched_setaffinity"),
            SyscallRuleSet::new_allow("sched_getaffinity"),
            SyscallRuleSet::new_allow("io_setup"),
            SyscallRuleSet::new_allow("io_destroy"),
            SyscallRuleSet::new_allow("io_getevents"),
            SyscallRuleSet::new_allow("io_submit"),
            SyscallRuleSet::new_allow("io_cancel"),
            SyscallRuleSet::new_allow("lookup_dcookie"),
            SyscallRuleSet::new_allow("epoll_create"),
            SyscallRuleSet::new_allow("remap_file_pages"),
            SyscallRuleSet::new_allow("set_tid_address"),
            SyscallRuleSet::new_allow("timer_create"),
            SyscallRuleSet::new_allow("timer_settime"),
            SyscallRuleSet::new_allow("timer_gettime"),
            SyscallRuleSet::new_allow("timer_getoverrun"),
            SyscallRuleSet::new_allow("timer_delete"),
            SyscallRuleSet::new_allow("clock_settime"),
            SyscallRuleSet::new_allow("clock_gettime"),
            SyscallRuleSet::new_allow("clock_getres"),
            SyscallRuleSet::new_allow("clock_nanosleep"),
            SyscallRuleSet::new_allow("exit_group"),
            SyscallRuleSet::new_allow("epoll_wait"),
            SyscallRuleSet::new_allow("epoll_ctl"),
            SyscallRuleSet::new_allow("tgkill"),
            SyscallRuleSet::new_allow("utimes"),
            SyscallRuleSet::new_allow("mbind"),
            SyscallRuleSet::new_allow("set_mempolicy"),
            SyscallRuleSet::new_allow("get_mempolicy"),
            SyscallRuleSet::new_allow("mq_open"),
            SyscallRuleSet::new_allow("mq_timedsend"),
            SyscallRuleSet::new_allow("mq_timedreceive"),
            SyscallRuleSet::new_allow("mq_notify"),
            SyscallRuleSet::new_allow("mq_getsetattr"),
            SyscallRuleSet::new_allow("kexec_load"),
            SyscallRuleSet::new_allow("waitid"),
            SyscallRuleSet::new_allow("add_key"),
            SyscallRuleSet::new_allow("request_key"),
            SyscallRuleSet::new_allow("keyctl"),
            SyscallRuleSet::new_allow("ioprio_set"),
            SyscallRuleSet::new_allow("ioprio_get"),
            SyscallRuleSet::new_allow("inotify_init"),
            SyscallRuleSet::new_allow("inotify_add_watch"),
            SyscallRuleSet::new_allow("inotify_rm_watch"),
            SyscallRuleSet::new_allow("migrate_pages"),
            SyscallRuleSet::new_allow("openat"),
            SyscallRuleSet::new_allow("mkdirat"),
            SyscallRuleSet::new_allow("mknodat"),
            SyscallRuleSet::new_allow("fchownat"),
            SyscallRuleSet::new_allow("futimesat"),
            SyscallRuleSet::new_allow("newfstatat"),
            SyscallRuleSet::new_allow("unlinkat"),
            SyscallRuleSet::new_allow("renameat"),
            SyscallRuleSet::new_allow("linkat"),
            SyscallRuleSet::new_allow("symlinkat"),
            SyscallRuleSet::new_allow("readlinkat"),
            SyscallRuleSet::new_allow("fchmodat"),
            SyscallRuleSet::new_allow("faccessat"),
            SyscallRuleSet::new_allow("pselect6"),
            SyscallRuleSet::new_allow("ppoll"),
            SyscallRuleSet::new_allow("unshare"),
            SyscallRuleSet::new_allow("set_robust_list"),
            SyscallRuleSet::new_allow("get_robust_list"),
            SyscallRuleSet::new_allow("splice"),
            SyscallRuleSet::new_allow("tee"),
            SyscallRuleSet::new_allow("sync_file_range"),
            SyscallRuleSet::new_allow("vmsplice"),
            SyscallRuleSet::new_allow("move_pages"),
            SyscallRuleSet::new_allow("utimensat"),
            SyscallRuleSet::new_allow("epoll_pwait"),
            SyscallRuleSet::new_allow("signalfd"),
            SyscallRuleSet::new_allow("timerfd_create"),
            SyscallRuleSet::new_allow("eventfd"),
            SyscallRuleSet::new_allow("fallocate"),
            SyscallRuleSet::new_allow("timerfd_settime"),
            SyscallRuleSet::new_allow("timerfd_gettime"),
            SyscallRuleSet::new_allow("accept4"),
            SyscallRuleSet::new_allow("signalfd4"),
            SyscallRuleSet::new_allow("eventfd2"),
            SyscallRuleSet::new_allow("epoll_create1"),
            SyscallRuleSet::new_allow("dup3"),
            SyscallRuleSet::new_allow("pipe2"),
            SyscallRuleSet::new_allow("inotify_init1"),
            SyscallRuleSet::new_allow("preadv"),
            SyscallRuleSet::new_allow("pwritev"),
            SyscallRuleSet::new_allow("rt_tgsigqueueinfo"),
            SyscallRuleSet::new_allow("perf_event_open"),
            SyscallRuleSet::new_allow("recvmmsg"),
            SyscallRuleSet::new_allow("fanotify_init"),
            SyscallRuleSet::new_allow("fanotify_mark"),
            SyscallRuleSet::new_allow("prlimit64"),
            SyscallRuleSet::new_allow("name_to_handle_at"),
            SyscallRuleSet::new_allow("open_by_handle_at"),
            SyscallRuleSet::new_allow("clock_adjtime"),
            SyscallRuleSet::new_allow("syncfs"),
            SyscallRuleSet::new_allow("sendmmsg"),
            SyscallRuleSet::new_allow("setns"),
            SyscallRuleSet::new_allow("getcpu"),
            SyscallRuleSet::new_allow("process_vm_readv"),
            SyscallRuleSet::new_allow("process_vm_writev"),
            SyscallRuleSet::new_allow("process_madvise"),
        ];

        let action = SeccompAction::Allow;
        SeccompFilter::new(allow_rules, action)
    }

    #[cfg(not(feature = "seccomp"))]
    pub fn create_filter(&self) -> () {
        ()
    }

    pub fn enable(&self) {
        self.enabled.store(true, Ordering::Relaxed);
    }

    pub fn disable(&self) {
        self.enabled.store(false, Ordering::Relaxed);
    }

    pub fn is_enabled(&self) -> bool {
        self.enabled.load(Ordering::Relaxed)
    }
}

impl Default for WindowsSeccompFilter {
    fn default() -> Self {
        Self::new(true)
    }
}
