[build]
rustflags = [
    # DENY - nghiêm trọng
    "-Dclippy::unwrap_in_test",
    "-Dclippy::unwrap_used",
    "-Dclippy::expect_used",
    "-Dclippy::print_stdout",
    "-Dclippy::print_stderr",
    "-Dclippy::panic",
    "-Dclippy::allow_attributes",
    "-Dclippy::allow_attributes_without_reason",
    "-Dunused_imports",
    "-Dunused_extern_crates",
    "-Dnonstandard_style",
    
    # WARN - placeholder và code chưa hoàn thiện
    "-Wclippy::unimplemented",
    "-Wclippy::todo",
    "-Wclippy::option_if_let_else",
    "-Wclippy::needless_option_as_ref",
    "-Wclippy::option_unwrap_used",
    "-Wunused_variables",
    "-Wdead_code",
    
    # ALLOW - một số warning không quan trọng
    "-Amissing-docs",      # bỏ qua missing documentation
    "-Aunused-variables",  # cho phép _tên_biến
    "-Adead-code",         # cho phép code chưa dùng
]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
