//! Spiking Neural Network (SNN) processor for real‑time event handling.
//! Uses Leaky Integrate‑and‑Fire (LIF) neurons to respond to eBPF spikes.

use common::ring_buffer::RingBuffer;
use parking_lot::RwLock;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::thread;
use std::time::{Duration, Instant};
use tracing::info;

const SPIKE_RING_SIZE: usize = 4096;
const ACTION_RING_SIZE: usize = 1024;

/// Spike event from eBPF cold page detector.
#[derive(Debug, Clone, Copy)]
pub struct SpikeEvent {
    pub pid: u32,
    pub vaddr: u64,
    pub timestamp_ns: u64,
}

/// Action generated by SNN (page-out command).
pub type SnnAction = (u32, u64);

/// LIF neuron parameters.
#[derive(Clone)]
struct LifNeuron {
    v: f32,
    leak: f32,
    threshold: f32,
    reset: f32,
    weight: f32,
}

impl LifNeuron {
    fn new(leak: f32, threshold: f32, reset: f32, weight: f32) -> Self {
        Self {
            v: 0.0,
            leak,
            threshold,
            reset,
            weight,
        }
    }

    fn step(&mut self, input: f32) -> bool {
        self.v = self.v * self.leak + input * self.weight;
        if self.v >= self.threshold {
            self.v = self.reset;
            true
        } else {
            false
        }
    }
}

/// SNN processor that monitors spike events and triggers actions.
pub struct LinuxSnnProcessor {
    neurons: Arc<RwLock<Vec<LifNeuron>>>,
    spike_rb: Arc<parking_lot::Mutex<RingBuffer<SpikeEvent>>>,
    action_rb: Arc<parking_lot::Mutex<RingBuffer<SnnAction>>>,
    running: Arc<AtomicBool>,
    thread_handle: Option<thread::JoinHandle<()>>,
    stats: Arc<RwLock<SnnStats>>,
}

#[derive(Default, Clone)]
struct SnnStats {
    total_spikes: u64,
    decisions_made: u64,
    last_spike_time: Option<Instant>,
}

impl LinuxSnnProcessor {
    pub fn new(num_neurons: usize) -> Self {
        let neurons = (0..num_neurons)
            .map(|_| LifNeuron::new(0.95, 1.0, 0.0, 1.0))
            .collect();
        Self {
            neurons: Arc::new(RwLock::new(neurons)),
            spike_rb: Arc::new(parking_lot::Mutex::new(RingBuffer::new(SPIKE_RING_SIZE))),
            action_rb: Arc::new(parking_lot::Mutex::new(RingBuffer::new(ACTION_RING_SIZE))),
            running: Arc::new(AtomicBool::new(false)),
            thread_handle: None,
            stats: Arc::new(RwLock::new(SnnStats::default())),
        }
    }

    pub fn send_event(&self, event: SpikeEvent) -> Result<(), String> {
        if self.spike_rb.lock().push(event) {
            Ok(())
        } else {
            Err("Spike ring buffer full".to_string())
        }
    }

    pub fn poll_action(&self) -> Option<SnnAction> {
        self.action_rb.lock().pop()
    }

    pub fn start(&mut self) {
        if self.running.load(Ordering::Relaxed) {
            return;
        }
        self.running.store(true, Ordering::Relaxed);
        let running = self.running.clone();
        let spike_rb = self.spike_rb.clone();
        let action_rb = self.action_rb.clone();
        let neurons = self.neurons.clone();
        let stats = self.stats.clone();

        let handle = thread::spawn(move || {
            let mut last_stats_log = Instant::now();
            let neuron_len = neurons.read().len();

            while running.load(Ordering::Relaxed) {
                let event = {
                    let mut rb = spike_rb.lock();
                    rb.pop()
                };

                if let Some(event) = event {
                    {
                        let mut st = stats.write();
                        st.total_spikes += 1;
                        st.last_spike_time = Some(Instant::now());
                    }

                    let idx = (event.vaddr as usize) % neuron_len;
                    let mut neurons_guard = neurons.write();
                    let neuron = &mut neurons_guard[idx];

                    if neuron.step(1.0) {
                        let action = (event.pid, event.vaddr);
                        let _ = action_rb.lock().push(action);
                        let mut st = stats.write();
                        st.decisions_made += 1;
                    }
                } else {
                    thread::sleep(Duration::from_micros(100));
                }

                if last_stats_log.elapsed() >= Duration::from_secs(10) {
                    let st = stats.read();
                    info!(
                        "SNN stats: spikes={}, decisions={}, last_spike={:?}",
                        st.total_spikes, st.decisions_made, st.last_spike_time
                    );
                    last_stats_log = Instant::now();
                }
            }
            info!("SNN processor stopped.");
        });
        self.thread_handle.replace(handle);
    }

    pub fn stop(&mut self) {
        self.running.store(false, Ordering::Relaxed);
        if let Some(handle) = self.thread_handle.take() {
            let _ = handle.join();
        }
    }

    pub fn reset(&self) {
        let mut neurons = self.neurons.write();
        for n in neurons.iter_mut() {
            n.v = 0.0;
        }
    }

    pub fn stats(&self) -> (u64, u64) {
        let st = self.stats.read();
        (st.total_spikes, st.decisions_made)
    }
}

impl Drop for LinuxSnnProcessor {
    fn drop(&mut self) {
        self.stop();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::thread;
    use std::time::Duration;

    #[test]
    fn test_snn_processor() {
        let mut processor = LinuxSnnProcessor::new(16);
        processor.start();

        for i in 0..10 {
            let event = SpikeEvent {
                pid: 1234,
                vaddr: 0x7f000000 + i * 4096,
                timestamp_ns: 0,
            };
            processor.send_event(event).ok();
            thread::sleep(Duration::from_micros(10));
        }

        thread::sleep(Duration::from_millis(100));

        let mut actions = 0;
        while let Some(_) = processor.poll_action() {
            actions += 1;
        }
        assert!(actions > 0);

        processor.stop();
    }
}
