use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = match env::var("CARGO_MANIFEST_DIR") {
        Ok(dir) => dir,
        Err(_) => {
            eprintln!("CARGO_MANIFEST_DIR not set");
            std::process::exit(1);
        }
    };

    let crate_path = PathBuf::from(&crate_dir);
    let parent1 = match crate_path.parent() {
        Some(p) => p,
        None => {
            eprintln!("Failed to get workspace root (parent of crate dir)");
            std::process::exit(1);
        }
    };
    let workspace_root = match parent1.parent() {
        Some(p) => p.to_path_buf(),
        None => {
            eprintln!("Failed to get workspace root (parent of parent)");
            std::process::exit(1);
        }
    };

    let include_dir = workspace_root.join("include");
    std::fs::create_dir_all(&include_dir).ok();

    let header_path = include_dir.join("aios_bindings.h");

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/bindings.rs");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        style: cbindgen::Style::Both,
        includes: vec!["stdint.h".to_string(), "stdbool.h".to_string()],
        header: Some("/* Auto-generated by cbindgen. Do not edit. */".to_string()),
        ..Default::default()
    };

    let bindings = match cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .exclude_item("loom_tests")
        .exclude_item("snn_latency")
        .generate()
    {
        Ok(b) => b,
        Err(e) => {
            eprintln!("Failed to generate bindings: {}", e);
            std::process::exit(1);
        }
    };

    bindings.write_to_file(&header_path);

    println!("cargo:include={}", include_dir.display());
}
