use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = PathBuf::from(&crate_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf();
    let include_dir = workspace_root.join("include");
    std::fs::create_dir_all(&include_dir).ok();

    let header_path = include_dir.join("aios_bindings.h");

    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/bindings.rs");

    let config = cbindgen::Config {
        language: cbindgen::Language::C,
        style: cbindgen::Style::Both,
        includes: vec!["stdint.h".to_string(), "stdbool.h".to_string()],
        header: Some("/* Auto-generated by cbindgen. Do not edit. */".to_string()),
        ..Default::default()
    };

    let bindings = cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .exclude_item("loom_tests")
        .exclude_item("snn_latency")
        .generate()
        .expect("Unable to generate bindings");

    bindings.write_to_file(&header_path);

    println!("cargo:include={}", include_dir.display());
}
